### ISSUE TITLE
undesirable .*.yml files in source release ball

### ISSUE THREAD

**Issue by jgmbenoit** [gap-packages/FactInt#15]
Please remove .codecov.yml and .travis.yml from the release tar ball (for future releases).

**Comment by fingolfin** [comment]
Why?

**Comment by jgmbenoit** [comment]
because they are useless outside the git repository (unless I missed something) ?

**Comment by fingolfin** [comment]
I actually think there is some merit to @jgmbenoit's request, and just submitted PR #18 to take care of it.
