### ISSUE TITLE
Factint is not multithreaded

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-packages/FactInt#2]
My change ( #1 ) makes factint work on the 'main thread' in HPC-GAP, but still not on any other threads.

Making it work on other threads will require placing locks around all of the caches which factint keeps. I am happy to work on this, but it will require quite a lot of code changes, so I wanted to check you would be happy, before I started.

**Comment by Stefan-Kohl** [comment]
I have just merged your pull request (thanks!).

Does placing locks around all of the caches have any drawbacks, e.g. a non-negligible slowdown?
- If not, then please go ahead and implement the changes!
- If yes, it may make sense to have two versions of FactInt --
   one for the 'usual' GAP, and one for HPC-GAP.
As I don't know much about HPC-GAP so far, I cannot say much else on this.

**Comment by olexandr-konovalov** [comment]
FactInt is now disables in HPC-GAP tests: see https://github.com/gap-system/gap/issues/3025 and https://github.com/gap-system/gap/pull/3039.
