### ISSUE TITLE
Using ReleaseTools and GitHubPagesForGAP

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/FactInt#4]
The suggestion is to use https://github.com/gap-system/ReleaseTools and 
https://github.com/gap-system/GitHubPagesForGAP to set up a webpage https://gap-packages.github.io/FactInt/ for this package.

**Comment by olexandr-konovalov** [comment]
@Stefan-Kohl to remind about this suggestion of mine - will you be happy for me to do this and to publish a new release?

**Comment by Stefan-Kohl** [comment]
Yes, thanks. You are welcome!

**Comment by olexandr-konovalov** [comment]
Duplicating part of my email from yesterday, just in case.

I have rebased December commits in FactInt and edited the history to make them atomic: you can see what happens here in my fork

https://github.com/alex-konovalov/FactInt/commits/master

@Stefan-Kohl If this looks OK to you, then I will force-push this to the main FactInt repository. In this case if you have clones/forks of this repository, their history will not be in sync and you need to reset them. Looking at the number of forks of FactInt (only Max and me have them) that does not sound like a problem. For local clones, to reset them, you will have to use

     git fetch origin
     git reset --hard origin/master

or in doubt just delete the clone and make a new one.

As @Stefan-Kohl suggested to me, I am happy to become a maintainer of FactInt, and we agreed to will use releaseTools and host the package webpage on GitHub pages.

**Comment by Stefan-Kohl** [comment]
@alex-konovalov Yes, the rebased commit history looks OK to me -- thank you. -- And I am glad to welcome you as a maintainer of FactInt!

**Comment by olexandr-konovalov** [comment]
Thanks! So, I've just updated the main repository, so please update your forks/clones @Stefan-Kohl and @fingolfin (and rebase existing PR #5).

This is not something I would like to do often. What about protecting the master branch (https://help.github.com/articles/defining-the-mergeability-of-pull-requests/) - I am using this for some of my packages (as well as we use it in the main GAP repository).

@Stefan-Kohl for you this will mean that you will make changes in a fork of this repository under your https://github.com/Stefan-Kohl account, whenever via web-interface or in a clone, but this does not change much in the way how you make changes, I think (except that you will have to submit changes via pull requests, but this is an essential core skill to learn).

**Comment by olexandr-konovalov** [comment]
Now version 1.6.1 published at https://gap-packages.github.io/FactInt/. Should be picked up by the package update mechanism tomorrow (provided @Stefan-Kohl merges https://github.com/Stefan-Kohl/stefan-kohl.github.io/pull/6).

**Comment by Stefan-Kohl** [comment]
Excellent.

**Comment by olexandr-konovalov** [comment]
@Stefan-Kohl please remember to merge https://github.com/Stefan-Kohl/stefan-kohl.github.io/pull/6
