### ISSUE TITLE
Is the 'version' file still needed?

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/FactInt#7]
@Stefan-Kohl Perhaps this file

https://github.com/gap-packages/FactInt/blob/1fd1e8d0c9eb03bf2243d8c168a1a4cf721587e1/version#L1

seems not to be used anywhere and may be deleted?

**Comment by olexandr-konovalov** [comment]
@Stefan-Kohl oh I see now `Version <#Include SYSTEM "../version">` in `doc/main.xml`. Then let it stay there at least for now.

**Comment by Stefan-Kohl** [comment]
@alex-konovalov If you use some tools to conveniently increment the version number of a package everywhere when preparing a release, then you can of course adjust things to use these tools for FactInt as well.

**Comment by fingolfin** [comment]
Using AutoDoc to prepare the title page would also take care of this.
